openapi: 3.0.3
info:
  title: Greeting Service API
  description: This is a simple API for a Greeting Service.
  version: 1.0.0
x-wso2-disable-security: true
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /greeting:
    get:
      summary: Returns a greeting
      description: Returns a simple JSON greeting message.
      responses:
        '200':
          description: A JSON object with a greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Hello, World"
        '500':
          description: Internal Server Error
